### ISSUE TITLE
2차 세미나

### ISSUE THREAD

**Issue by meenyweeny** [GO-SOPT-SERVER/LeeKyoungMin#3]

**Comment by pcsoyeon** [comment]
기대가 됩니다만?

**Comment by meenyweeny** [comment]
> 기대가 됩니다만?

이경민 서버 개발자 데뷔식

**Comment by hansh0101** [comment]
아직 2차 세미나도 안 했는데 2차 세미나 이슈를 팠네요 오늘 코드 안 짜고 잔디 심으려는 심보가 고약합니다 정말

**Comment by meenyweeny** [comment]
> 아직 2차 세미나도 안 했는데 2차 세미나 이슈를 팠네요 오늘 코드 안 짜고 잔디 심으려는 심보가 고약합니다 정말

완벽한 간파
